version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8  # For Apple Silicon
    container_name: boomershub_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: boomershub_task
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3307:3306"  # Changed from 3306 to avoid conflicts
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - boomershub_network

volumes:
  mysql_data:

networks:
  boomershub_network:
    driver: bridge 